/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as BoardsBoardIdImport } from './routes/boards.$boardId'
import { Route as BoardsBoardIdTaskTaskIdImport } from './routes/boards.$boardId.task.$taskId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const BoardsBoardIdRoute = BoardsBoardIdImport.update({
  path: '/boards/$boardId',
  getParentRoute: () => rootRoute,
} as any)

const BoardsBoardIdTaskTaskIdRoute = BoardsBoardIdTaskTaskIdImport.update({
  path: '/task/$taskId',
  getParentRoute: () => BoardsBoardIdRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/boards/$boardId': {
      preLoaderRoute: typeof BoardsBoardIdImport
      parentRoute: typeof rootRoute
    }
    '/boards/$boardId/task/$taskId': {
      preLoaderRoute: typeof BoardsBoardIdTaskTaskIdImport
      parentRoute: typeof BoardsBoardIdImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  BoardsBoardIdRoute.addChildren([BoardsBoardIdTaskTaskIdRoute]),
])

/* prettier-ignore-end */
